version: '3.8'

services:
  redis:
    image: 'redis:5'
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - 'redis_data:/data'
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: