# Generated by Django 4.0.4 on 2022-04-13 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_captured',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), default=[], size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='white_captured',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), default=[], size=10),
            preserve_default=False,
        ),
    ]
