# Generated by Django 4.0.4 on 2022-04-20 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_actioncount_game_corplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='readytoblitz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2), null=True, size=2),
        ),
    ]
