# Generated by Django 4.0.4 on 2022-04-20 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_readytoblitz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='readytoblitz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2), default=['', ''], size=2),
            preserve_default=False,
        ),
    ]
